(Chore) : Upgrade all Package Dependency , FIX GULP-SaSS issue. Proj…
moesaid/cleopatra pull request #16
Opened 2022-04-28 10:27 UTC by naime-hossain

1. Update All Dependency 
2. 2. Fix Depcracation error while run yarn / npm install
3. fix gulp-sass issue

2022-10-18 09:22 UTC, naime-hossain commented
@moesaid can you check the pull request

2022-10-18 13:53 UTC, moesaid commented
> @moesaid can you check the pull request

Thanks for your time!!! i will make sure to review the PR this weekend! thanks again Hossain!

2024-03-31 01:41 UTC, alexis-coulombe commented
Any news @moesaid  ? 

Thanks for his work, i successfully installed the project using his repository.

2024-07-16 10:33 UTC, naime-hossain commented
@moesaid can you check the PR  and merge? Thanks

2024-08-02 02:39 UTC, moesaid requested changes

2024-08-02 02:39 UTC, moesaid commented on tailwind.config.js
@ naime-hossain Hey bud ! Sorry for being out of sync here. Could you explain why removing the customized config and going pair metal?

2024-08-02 02:43 UTC, moesaid commented on tailwind.config.js
never mind, I gotcha!

2024-08-02 02:43 UTC, merged